#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-09-28 16:09:50
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://tanakamura.github.io/pllp/docs/asm_language.html
# Description:	---
#


.PHONY: clean run debug

run:
	gcc add.s

debug:
	gdb a.out

clean:
	rm a.out
