#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-09-28 16:09:50
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
# Description:	---
#


.PHONY: clean run debug

run:
	gcc add.s

debug:
	gdb a.out

clean:
	rm a.out
