#
# FileName:     Makefile
# Author: 		8ucchiman
# CreatedDate:  2023-09-07 12:13:44
# LastModified: 2023-02-03 21:27:40 +0900
# Reference: 	https://qiita.com/chibi929/items/b8c5f36434d5d3fbfa4a
#               http://nw.tsuda.ac.jp/lec/arm64/mac_m1/
# Description:	---
#


GCC=/usr/bin/gcc
.PHONY=clean

sample2b.s: sample2b.c
	${GCC} -O -S sample2b.c


clean:
	rm sample2b.s
